apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: openstack-unified
  namespace: openstack
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: openstack.rpcu.vpn
  routes:
    # Keystone - /keystone -> keystone-api:5000
    - conditions:
        - prefix: /keystone
      services:
        - name: keystone-api
          port: 5000

    # Glance - /glance -> glance-api:9292
    - conditions:
        - prefix: /glance
      services:
        - name: glance-api
          port: 9292

    # Nova - /nova -> nova-api:8774
    - conditions:
        - prefix: /nova/metadata
      services:
        - name: nova-metadata
          port: 8775

    - conditions:
        - prefix: /nova
      services:
        - name: nova-api
          port: 8774

    # Neutron - /neutron -> neutron-server:9696
    - conditions:
        - prefix: /neutron
      services:
        - name: neutron-server
          port: 9696

    # Cinder - /cinder/v3 -> cinder-api:8776
    - conditions:
        - prefix: /cinder/v3
      services:
        - name: cinder-api
          port: 8776

    - conditions:
        - prefix: /cinder/v2
      services:
        - name: cinder-api
          port: 8776

    - conditions:
        - prefix: /cinder/v1
      services:
        - name: cinder-api
          port: 8776

    # Placement - /placement -> placement-api:8778
    - conditions:
        - prefix: /placement
      services:
        - name: placement-api
          port: 8778

    # Nova VNC Proxy - /vnc/ -> nova-novncproxy:6080 (with websockets)
    - conditions:
        - prefix: /vnc/
      services:
        - name: nova-novncproxy
          port: 6080
      enableWebsockets: true
      pathRewritePolicy:
        replacePrefix:
          - prefix: /vnc/
            replacement: /

    # Websocket for noVNC - /websockify -> nova-novncproxy:6080
    - conditions:
        - prefix: /websockify
      services:
        - name: nova-novncproxy
          port: 6080
      enableWebsockets: true

    # Default route - / -> horizon:80 (dashboard)
    - conditions:
        - prefix: /
      services:
        - name: horizon-int
          port: 80
