apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: yaook-internal
spec:
  ca:
    secretName: root-rpcu
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
