apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-provider-openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secrets
    kind: SecretStore
  target:
    name: crossplane-provider-openstack
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "auth_url": "https://keystone.yaook.svc:5000",
            "user_name": "{{ .username }}",
            "password": "{{ .password }}",
            "project_domain_name": "{{ .project_domain_name }}",
            "tenant_name": "{{ .tenant_name }}",
            "user_domain_name": "{{ .user_domain_name }}",
            "region": "hetzner",
            "insecure": "true",
            "endpoint_type": "internal"
          }
  data:
    - secretKey: username
      remoteRef:
        key: keystone-admin
        property: OS_USERNAME
    - secretKey: password
      remoteRef:
        key: keystone-admin
        property: OS_PASSWORD
    - secretKey: project_domain_name
      remoteRef:
        key: keystone-admin
        property: OS_PROJECT_DOMAIN_NAME
    - secretKey: user_domain_name
      remoteRef:
        key: keystone-admin
        property: OS_USER_DOMAIN_NAME
    - secretKey: tenant_name
      remoteRef:
        key: keystone-admin
        property: OS_PROJECT_NAME
