apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keystone-oidc-crypto-passphrase
spec:
  length: 32
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystone-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secrets
    kind: SecretStore
  target:
    name: keystone-vhost-conf
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        keystone-api-vhost.conf: |
          # OIDC
          LoadModule auth_openidc_module modules/mod_auth_openidc.so
          # Require valid-user
          LoadModule authz_user_module modules/mod_authz_user.so
          # AuthType
          LoadModule authn_core_module modules/mod_authn_core.so

          OIDCXForwardedHeaders X-Forwarded-Proto X-Forwarded-Port X-Forwarded-Host
          OIDCClaimPrefix "OIDC-"
          OIDCClaimDelimiter ";"
          OIDCResponseType "code"
          OIDCScope "openid email profile groups"

          OIDCCryptoPassphrase {{ .crypto_passphrase }}
          OIDCProviderMetadataURL https://rpcu-gabeck.eu1.zitadel.cloud/.well-known/openid-configuration
          OIDCOAuthVerifyJwksUri https://rpcu-gabeck.eu1.zitadel.cloud/oauth/v2/keys
          OIDCClientID {{ .client_id }}
          OIDCClientSecret {{ .client_secret }}
          OIDCRedirectURI /redirect_uri

          <Location /redirect_uri>
            Require valid-user
            AuthType openid-connect
          </Location>
          <LocationMatch /v3/OS-FEDERATION/identity_providers/.*?/protocols/openid/auth>
            Require valid-user
            AuthType auth-openidc
          </LocationMatch>
          <Location /v3/auth/OS-FEDERATION/websso/openid>
            Require valid-user
            AuthType openid-connect
          </Location>
          <LocationMatch /v3/auth/OS-FEDERATION/identity_providers/.*?/protocols/openid/websso>
            Require valid-user
            AuthType openid-connect
          </LocationMatch>
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keystone-oidc-crypto-passphrase
      rewrite:
        - regexp:
            source: "password"
            target: "crypto_passphrase"
  data:
    - secretKey: client_id
      remoteRef:
        key: openstack-oidc
        property: attribute.client_id
    - secretKey: client_secret
      remoteRef:
        key: openstack-oidc
        property: attribute.client_secret
