apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-client-cinder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rook-ceph-secrets
    kind: SecretStore
  target:
    name: rook-ceph-client-cinder
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rook-ceph-client-cinder
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-client-glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rook-ceph-secrets
    kind: SecretStore
  target:
    name: rook-ceph-client-glance
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rook-ceph-client-glance
