apiVersion: yaook.cloud/v1
kind: HorizonDeployment
metadata:
  name: horizon
spec:
  extraSettings:
    sources:
      - secret:
          name: horizon-websso
  keystoneRef:
    name: keystone
  replicas: 1
  ingress:
    createIngress: false
    fqdn: "os.rpcu.vpn"
    port: 443
  issuerRef:
    name: yaook-internal
  targetRelease: "2025.1"
