apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nova
  namespace: yaook
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: nova.rpcu.vpn
  routes:
    - conditions:
        - prefix: /
      services:
        - name: nova-api
          port: 8775
          protocol: tls
