apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: keystone
  namespace: yaook
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: keystone.rpcu.vpn
  routes:
    - conditions:
        - prefix: /
      services:
        - name: keystone
          port: 5001
          protocol: tls
