apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: glance
  namespace: yaook
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: glance.rpcu.vpn
  routes:
    - conditions:
        - prefix: /
      services:
        - name: glance-api
          port: 9293
          protocol: tls
