apiVersion: yaook.cloud/v1
kind: KeystoneDeployment
metadata:
  name: keystone
spec:
  extraProjected:
    sources:
      - secret:
          name: keystone-vhost-conf
  database:
    replicas: 1
    timeoutClient: 300
    proxy: {}
    backup:
      schedule: "0 * * * *"
  memcached:
    memory: 1024
    connections: 2000
  api:
    ingress:
      createIngress: false
      fqdn: "keystone.rpcu.vpn"
      port: 443
    replicas: 1
    wsgiProcesses: 10
  keystoneConfig:
    auth:
      methods: ["password", "token", "openid", "application_credential"]
    openid:
      # OIDCClaimPrefix: "OIDC-"
      remote_id_attribute: HTTP_OIDC_ISS
    federation:
      trusted_dashboard:
        - https://os.rpcu.vpn/auth/websso/
    DEFAULT:
      # specify CADF to enable advanced audit logging
      notification_format: "cadf"
    oslo_messaging_notifications:
      # select an oslo.messaging notifications driver to activate audit logging
      driver:
        - log
    token:
      expiration: 86400
    database:
      # (optional) connection_recycle_time hould always be ~10%
      # smaller than the haproxy timeoutClient
      connection_recycle_time: 280
  policy:
    "admin_required": "role:admin or is_admin:1"
  region:
    name: hetzner
  issuerRef:
    name: yaook-internal
  targetRelease: "2025.1"
