apiVersion: yaook.cloud/v1
kind: KeystoneDeployment
metadata:
  name: keystone
spec:
  api:
    ingress:
      createIngress: false
      fqdn: keystone.rpcu.vpn
      ingressClassName: nginx
      port: 443
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    wsgiProcesses: 10
  database:
    backup:
      mysqldump: false
      schedule: 0 * * * *
      warmKeepMax: "3"
    proxy:
      replicas: 2
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    storageSize: 8Gi
    timeoutClient: 300
    tolerateNodeDown: false
  extraProjected:
    sources:
      - secret:
          name: keystone-vhost-conf
  issuerRef:
    name: yaook-internal
  keyRotationSchedule: 0 0 * * *
  keystoneConfig:
    DEFAULT:
      notification_format: cadf
    auth:
      methods:
        - password
        - token
        - openid
        - application_credential
    database:
      connection_recycle_time: 280
    federation:
      trusted_dashboard:
        - https://os.rpcu.vpn/auth/websso/
    openid:
      remote_id_attribute: HTTP_OIDC_ISS
    oslo_messaging_notifications:
      driver:
        - log
    token:
      expiration: 86400
  memcached:
    connections: 2000
    memory: 1024
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  policy:
    admin_required: role:admin or is_admin:1
  region:
    name: hetzner
  targetRelease: "2025.1"
