apiVersion: yaook.cloud/v1
kind: NeutronDeployment
metadata:
  name: neutron-ovn
spec:
  api:
    ingress:
      createIngress: false
      fqdn: "neutron.rpcu.vpn"
      port: 443
    replicas: 6
    resources:
      neutron-api:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 3Gi
  database:
    proxy:
      replicas: 1
    backup:
      schedule: "0 * * * *"
    replicas: 1
    timeoutClient: 300
  issuerRef:
    name: yaook-internal
  keystoneRef:
    name: keystone
  messageQueue:
    replicas: 1
    resources:
      rabbitmq:
        requests:
          memory: 1G
          cpu: 1000m
        limits:
          memory: 2G
  memcached:
    connections: 1024
    memory: 512
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  neutronConfig:
    DEFAULT:
      debug: false
      global_physnet_mtu: 1400
      advertise_mtu: True
      enable_tcp_mss_clamping: True
      dnsmasq_dns_servers:
        - 172.16.0.254
    ovn:
      dns_servers:
        - 172.16.0.254
      ovn_emit_need_to_frag: True
  neutronML2Config:
    ml2:
      path_mtu: 1400
      physical_network_mtus: enp3s0:1400
    ml2_type_flat:
      flat_networks:
        - public
  novaRef:
    name: nova
  policy:
    "context_is_admin": "role:admin"
    "create_floatingip": "rule:context_is_admin or role:member"
    "create_floatingip:floating_ip_address": "rule:context_is_admin or role:member"
    "update_floatingip": "rule:context_is_admin or role:member"
    "delete_floatingip": "rule:context_is_admin or role:member"
    "get_floatingip": ""
  region:
    name: hetzner
  setup:
    ovn:
      northboundOVSDB:
        replicas: 3
        backup:
          schedule: 0 12 * * *
      northd:
        # northd remote probe interval (to nb or nb relay) can be adjusted individually
        remoteInactivityProbeMs: 60000
      southboundOVSDB:
        # recommended to increase inactivityProbe and raftElectionTimer at scale (default 5s/1s)
        inactivityProbeMs: 60000
        raftElectionTimerMs: 60000
        ovnRelay: # add this section to deploy ovn-relays
          # in large scale deployments, tune probe intervals separately for the ovsdb relays
          inactivityProbeMs: 120000
          remoteInactivityProbeMs: 60000
          replicas: 3
        replicas: 3
        backup:
          schedule: 0 12 * * *
      controller:
        # ovn-controller remote probe interval (to sb or sb relay) can be adjusted individually
        remoteInactivityProbeMs: 60000
        configTemplates:
          - nodeSelectors:
              - matchLabels: {}
            bridgeConfig:
              - bridgeName: br-ex
                uplinkDevice: enp3s0
                openstackPhysicalNetwork: "public"
  targetRelease: "2026.1"
