apiVersion: yaook.cloud/v1
kind: NovaDeployment
metadata:
  name: nova
spec:
  api:
    ingress:
      createIngress: false
      fqdn: nova.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      api:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
  compute:
    configTemplates:
      - nodeSelectors:
          - matchLabels: {}
        novaComputeConfig:
          DEFAULT:
            debug: false
            max_concurrent_builds: 5
            block_device_allocate_retries: 180
            block_device_allocate_retries_interval: 10
            cpu_allocation_ratio: 4.0
            ram_allocation_ratio: 1.0
            disk_allocation_ratio: 1.5
            reserved_host_memory_mb: 8192
            reserved_host_cpus: 2
          cinder:
            timeout: 600
          keystone_authtoken:
            os_region_name: hetzner
          libvirt:
            virt_type: kvm
            cpu_mode: host-passthrough
        volumeBackends:
          ceph:
            cephConfig: {}
            enabled: true
            keyringSecretName: rook-ceph-client-cinder
            user: cinder
            uuid: b3ab713d-912b-49ed-adaf-bd74368e567a
  conductor:
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      conductor:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
  database:
    api:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        mysqld:
          max_connections: 1337
          max_heap_table_size: 64M
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    cell0:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        galera:
          wsrep_slave_threads: 3
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    cell1:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        galera:
          wsrep_slave_threads: 3
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    placement:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        mysqld:
          max_connections: 1337
          max_heap_table_size: 64M
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
  databaseCleanup:
    clearAllEvents: false
    clearOnlyMigrationEvents: false
    deletionTimeRange: 60
    schedule: 0 0 * * *
  eviction:
    manager:
      deleteNode: true
      enabled: false
      interval: 15
      max_per_hour: 5
    maxParallelMigrations: 2
    netboxSetFailed: false
    volumeLockDurationSeconds: 30
  issuerRef:
    name: yaook-internal
  keystoneRef:
    kind: KeystoneDeployment
    name: keystone
  memcached:
    connections: 1024
    memory: 512
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  messageQueue:
    cell1:
      replicas: 1
      resources:
        rabbitmq:
          requests:
            cpu: 1000m
            memory: 1G
          limits:
            cpu: 2000m
            memory: 2G
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      tolerateNodeDown: false
  metadata:
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      metadata:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
  novaConfig:
    DEFAULT:
      debug: false
      osapi_compute_workers: 4
      metadata_workers: 4
    conductor:
      workers: 4
    scheduler:
      workers: 4
    database:
      max_pool_size: 20
      max_overflow: 30
  placement:
    ingress:
      createIngress: false
      fqdn: placement.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      api:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
  placementCleanup:
    schedule: 0 0 1 * *
  policy:
    context_is_admin: role:admin
  region:
    name: hetzner
  scheduler:
    replicas: 3
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      scheduler:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
  targetRelease: "2025.1"
  vnc:
    ingress:
      createIngress: false
      fqdn: vnc.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
    resources:
      vnc:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
