apiVersion: yaook.cloud/v1
kind: NovaDeployment
metadata:
  name: nova
spec:
  api:
    ingress:
      createIngress: false
      fqdn: nova.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  compute:
    configTemplates:
      - nodeSelectors:
          - matchLabels: {}
        novaComputeConfig:
          DEFAULT:
            debug: false
          keystone_authtoken:
            os_region_name: hetzner
          libvirt:
            virt_type: qemu
        volumeBackends:
          ceph:
            cephConfig: {}
            enabled: true
            keyringSecretName: rook-ceph-client-cinder
            user: cinder
            uuid: b3ab713d-912b-49ed-adaf-bd74368e567a
  conductor:
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  database:
    api:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        mysqld:
          max_connections: 1337
          max_heap_table_size: 64M
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    cell0:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        galera:
          wsrep_slave_threads: 3
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    cell1:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        galera:
          wsrep_slave_threads: 3
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
    placement:
      backup:
        mysqldump: false
        schedule: 0 * * * *
        warmKeepMax: "3"
      mysqlConfig:
        mysqld:
          max_connections: 1337
          max_heap_table_size: 64M
      proxy:
        replicas: 1
        scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      replicas: 1
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      timeoutClient: 300
      tolerateNodeDown: false
  databaseCleanup:
    clearAllEvents: false
    clearOnlyMigrationEvents: false
    deletionTimeRange: 60
    schedule: 0 0 * * *
  eviction:
    manager:
      deleteNode: true
      enabled: false
      interval: 15
      max_per_hour: 5
    maxParallelMigrations: 2
    netboxSetFailed: false
    volumeLockDurationSeconds: 30
  issuerRef:
    name: yaook-internal
  keystoneRef:
    kind: KeystoneDeployment
    name: keystone
  memcached:
    connections: 1024
    memory: 512
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  messageQueue:
    cell1:
      replicas: 1
      resources:
        rabbitmq:
          limits:
            cpu: 1000m
            memory: 1G
      scheduleRuleWhenUnsatisfiable: ScheduleAnyway
      storageSize: 8Gi
      tolerateNodeDown: false
  metadata:
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  novaConfig:
    DEFAULT:
      debug: false
  placement:
    ingress:
      createIngress: false
      fqdn: placement.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  placementCleanup:
    schedule: 0 0 1 * *
  policy:
    context_is_admin: role:admin
  region:
    name: hetzner
  scheduler:
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
  targetRelease: "2025.1"
  vnc:
    ingress:
      createIngress: false
      fqdn: vnc.rpcu.vpn
      ingressClassName: nginx
      port: 443
    publishEndpoint: true
    replicas: 1
    scheduleRuleWhenUnsatisfiable: ScheduleAnyway
