apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neutron
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: neutron
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: flux-system
  install:
    disableWait: true #https://github.com/fluxcd/flux2/discussions/1085#discussioncomment-473271
  upgrade:
    disableWait: true
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: neutron-values
