apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neutron
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: neutron
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: flux-system
  install:
    disableWait: true #https://github.com/fluxcd/flux2/discussions/1085#discussioncomment-473271
  upgrade:
    disableWait: true
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: neutron-values
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: neutron-ovs-agent-default
            patch: |
              - op: replace
                path: /spec/template/spec/securityContext/runAsUser
                value: 0
          - target:
              kind: DaemonSet
              name: neutron-ovs-agent-default
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/securityContext/runAsUser
                value: 0
          - target:
              kind: DaemonSet
              name: neutron-ovs-agent-default
            patch: |
              - op: remove
                path: /spec/template/spec/initContainers/0
