namespace: monitoring
resources:
  - grafana.yaml
  - mimir-datasource.yaml
  - dashboards/cluster-overview-dashboard.yaml
  - dashboards/pvc-storage-dashboard.yaml
  - dashboards/node-filesystem-dashboard.yaml
  - httproute.yaml
