namespace: monitoring
resources:
  - grafana.yaml
  - mimir-datasource.yaml
  - dashboards/cluster-overview-dashboard.yaml
  - dashboards/pvc-storage-dashboard.yaml
  - dashboards/node-filesystem-dashboard.yaml
  - dashboards/ceph-storage-dashboard.yaml
  - dashboards/openstack-control-plane-dashboard.yaml
  - dashboards/palworld-dashboard.yaml
  - dashboards/node-disk-io-dashboard.yaml
  - dashboards/pod-io-dashboard.yaml
  - dashboards/fluxcd-dashboard.yaml
  - dashboards/cert-manager-dashboard.yaml
  - dashboards/apiserver-dashboard.yaml
  - dashboards/sveltos-dashboard.yaml
  - dashboards/blackbox-dashboard.yaml
  - httproute.yaml
