namespace: yaook
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease-crds.yaml
  - helmrelease-infra-operator.yaml
  - helmrelease-keystone-operator.yaml
  - helmrelease-keystone-resources-operator.yaml
  - helmrelease-glance-operator.yaml
  - helmrelease-nova-operator.yaml
  - helmrelease-nova-compute-operator.yaml
  - helmrelease-neutron-operator.yaml
  - helmrelease-neutron-ovn-operator.yaml
  - helmrelease-horizon-operator.yaml
  - helmrelease-octavia-operator.yaml
  - helmrelease-designate-operator.yaml
  - helmrelease-cds-operator.yaml
