apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api-templates
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/cluster-api-templates
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: cluster-api-providers
