resources:
  - cilium.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - cluster-api-operator.yaml
  - cluster-api-providers.yaml
  - cluster-api-templates.yaml
  - capo-identity.yaml
  - orc.yaml
  - flux-operator.yaml
  - fluxcd/
  - clusters/
