resources:
  - cilium.yaml
  - cert-manager.yaml
  - gateway-api.yaml
  - kgateway-crds.yaml
  - kgateway.yaml
  - cert-manager-issuer.yaml
  - external-secrets.yaml
  - cluster-api-operator.yaml
  - cluster-api-providers.yaml
  - cluster-api-templates.yaml
  - capo-identity.yaml
  - orc.yaml
  - openstack-ccm-identity.yaml
  - openstack-ccm.yaml
  - external-snapshotter-crds.yaml
  - external-snapshotter.yaml
  - openstack-cinder-csi.yaml
  - csi-driver-nfs.yaml
  - external-dns.yaml
  - crossplane.yaml
  - crossplane-compositions.yaml
  - crossplane-zitadel.yaml
  - crossplane-openstack.yaml
  - crossplane-vault.yaml
  - crossplane-providers.yaml
  - crossplane-resources.yaml
  - dragonfly-operator.yaml
  - chihiro.yaml
  - vault.yaml
  - vault-unsealer.yaml
  - sveltos.yaml
  - kubernetes-rbac.yaml
  - flux-operator.yaml
  - kamaji.yaml
  - fluxcd/
  - monitoring.yaml
  - mimir.yaml
  - grafana.yaml
  - clusters.yaml
