apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: keystone
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: openstack
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: keystone-values
