apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keystone
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: keystone
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: flux-system
  upgrade:
    crds: CreateReplace
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Job
              name: keystone-ks-endpoints
            patch: |
              - op: add
                path: /spec/template/spec/initContainers/0/env/-
                value:
                  name: OS_SERVICE_ENDPOINT
                  value: "http://openstack.rpcu.vpn/keystone"
  valuesFrom:
    - kind: ConfigMap
      name: keystone-values
