# CCMCredential claim for the production project.
apiVersion: identity.rpcu.io/v1alpha1
kind: CCMCredential
metadata:
  name: production
  namespace: crossplane-system
spec:
  projectName: production
  projectId: 75aa5d153361400488a2d43a4fe629c3
