resources:
  - oidc-rbac.yaml
  - cilium.yaml
  - cilium-values.yaml
  - flux.yaml
  - openstack-ccm.yaml
  - openstack-cinder-csi.yaml
  - volume-snapshot-crds.yaml
  - volume-snapshot-controller.yaml
