apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
spec:
  parentRefs:
    - name: https
      namespace: kgateway-system
      sectionName: https
  hostnames:
    - "ceph.rpcu.vpn"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 7000
