apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji-crds
spec:
  interval: 5m
  chart:
    spec:
      chart: kamaji-crds
      version: "0.0.0+latest"
      sourceRef:
        kind: HelmRepository
        name: kamaji
        namespace: kamaji-system
