namespace: kamaji-system
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease-crds.yaml
  - helmrelease.yaml
  - etcd-pdb.yaml
configMapGenerator:
  - name: kamaji-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
