etcd:
  deploy: true
  persistence:
    storageClassName: csi-cinder-sc-delete
image:
  # renovate: datasource=docker depName=docker.io/clastix/kamaji
  tag: 26.6.2-edge
replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
kamaji-etcd:
  clusterDomain: "mgmt.local"
gatewayAPI:
  enabled: false
datastore:
  enabled: true
  name: default
