resources:
  - httproute-keystone.yaml
  - httproute-glance.yaml
  - httproute-neutron.yaml
  - httproute-nova.yaml
  - httproute-placement.yaml
  - httproute-vnc.yaml
  - httproute-cinder.yaml
  - httproute-horizon.yaml
  - httproute-octavia.yaml
  - httproute-designate.yaml
