apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: yaook-passthrough-listeners
  namespace: yaook # XListenerSet is namespaced
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: https
    namespace: kgateway-system
  listeners:
    - protocol: TLS
      port: 443
      name: yaook-passthrough-neutron
      hostname: "neutron.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-vnc
      hostname: "vnc.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-placement
      hostname: "placement.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-glance
      hostname: "glance.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-cinder
      hostname: "cinder.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-nova
      hostname: "nova.rpcu.vpn"
      tls:
        mode: Passthrough
    - protocol: TLS
      port: 443
      name: yaook-passthrough-keystone
      hostname: "keystone.rpcu.vpn"
      tls:
        mode: Passthrough
