apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: tlsroute-neutron
  namespace: yaook
spec:
  parentRefs:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough-neutron
  hostnames:
    - "neutron.rpcu.vpn"
  rules:
    - backendRefs:
        - name: neutron-api
          port: 9697
