apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
spec:
  parentRefs:
    - name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough
  hostnames:
    - "vnc.rpcu.vpn"
  rules:
    - backendRefs:
        - name: vnc
          port: 6080
