apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: tlsroute-vnc
spec:
  parentRefs:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough-vnc
  hostnames:
    - "vnc.rpcu.vpn"
  rules:
    - backendRefs:
        - name: vnc
          port: 6080
