apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: tlsroute-horizon
  namespace: yaook
spec:
  parentRefs:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough-horizon # Target the new TLS passthrough listener
  hostnames:
    - "os.rpcu.vpn"
  rules:
    - backendRefs:
        - name: horizon
          port: 8443
