apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: tlsroute-cinder
spec:
  parentRefs:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough-cinder
  hostnames:
    - "cinder.rpcu.vpn"
  rules:
    - backendRefs:
        - name: cinder-api
          port: 8777
