apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: tlsroute-nova
spec:
  parentRefs:
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: yaook-passthrough-listeners
      namespace: yaook
      sectionName: yaook-passthrough-nova
  hostnames:
    - "nova.rpcu.vpn"
  rules:
    - backendRefs:
        - name: nova-api
          port: 8775
