installCRDs: true

resources:
  controller:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi
  webhook:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  certController:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
