apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: placement
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: placement
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: flux-system
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: placement-values
