namespace: crossplane-system
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: crossplane-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
