resources:
  - cephblockpool.yaml
  - cephcluster.yaml
  - cephfilesystem.yaml
  - cephobjectstore.yaml
  - cephobjectstoreuser.yaml
  - cephnfs.yaml
  - openstack-clients.yaml
  - rook-ceph-config.yaml
  - storageclassrdb.yaml
  - storageclasscephfs.yaml
  - toolbox-deployment.yaml
  - gateway/
