resources:
  - cephblockpool.yaml
  - cephcluster.yaml
  - cephfilesystem.yaml
  - cephobjectstore.yaml
  - cephobjectstoreuser.yaml
  - mon-external-services.yaml
  - openstack-clients.yaml
  - storageclassrdb.yaml
  - storageclasscephfs.yaml
  - toolbox-deployment.yaml
  - gateway/
