namespace: monitoring
resources:
  - discord-secret.yaml
  - folder.yaml
  - notification-template-discord.yaml
  - contactpoint-discord.yaml
  - notification-policy.yaml
  - rules-node.yaml
  - rules-storage.yaml
  - rules-pods.yaml
  - rules-openstack.yaml
  - rules-diskio.yaml
  - rules-flux.yaml
  - rules-certmanager.yaml
  - rules-sveltos.yaml
  - rules-capi.yaml
