apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dike-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dike-manager-role
subjects:
  - kind: ServiceAccount
    name: dike-controller-manager
    namespace: dike-system
