apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cinder
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: cinder
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: flux-system
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: cinder-values
