apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook
spec:
  interval: 5m
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: "v1.19.0"
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
