namespace: kube-system
resources:
  - helmrepo.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: openstack-cinder-csi-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
