apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.16.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    l2announcements:
      enabled: true
    socketLB:
      hostNamespaceOnly: true
    kubeProxyReplacement: true
    k8sServiceHost: "10.0.0.5"
    k8sServicePort: 6443
    envoy:
      enabled: false
    cni:
      exclusive: false
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - "10.244.0.0/16"
        clusterPoolIPv4MaskSize: 23
