apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: mariadb
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openstack-helm
        namespace: openstack
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: mariadb-values
