resources:
  - namespace.yaml
  - clusterclass.yaml
  - templates/controlplane.yaml
  - templates/bootstrap.yaml
  - templates/infracluster.yaml
  - templates/infracluster-v2.yaml
  - templates/machines.yaml
