apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: external-network
spec:
  compositeTypeRef:
    apiVersion: networking.rpcu.io/v1alpha1
    kind: ExternalNetwork
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: external-network
            base:
              apiVersion: networking.openstack.m.crossplane.io/v1alpha1
              kind: NetworkV2
              spec:
                forProvider:
                  adminStateUp: true
                  external: true
                  shared: true
                  segments:
                    - networkType: flat
                      physicalNetwork: public
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.networkName
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.networkName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.networkName
                toFieldPath: metadata.labels["network"]
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.networkId
          - name: external-subnet
            base:
              apiVersion: networking.openstack.m.crossplane.io/v1alpha1
              kind: SubnetV2
              spec:
                forProvider:
                  enableDhcp: false
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.subnetName
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.cidr
                toFieldPath: spec.forProvider.cidr
              - type: FromCompositeFieldPath
                fromFieldPath: spec.gatewayIp
                toFieldPath: spec.forProvider.gatewayIp
              - type: FromCompositeFieldPath
                fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.networkId
                toFieldPath: spec.forProvider.networkId
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: spec.dnsNameservers
                toFieldPath: spec.forProvider.dnsNameservers
              - type: FromCompositeFieldPath
                fromFieldPath: spec.allocationPool
                toFieldPath: spec.forProvider.allocationPool
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.subnetId
          - name: external-router
            base:
              apiVersion: networking.openstack.m.crossplane.io/v1alpha1
              kind: RouterV2
              spec:
                forProvider:
                  adminStateUp: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.routerName
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.routerName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.networkId
                toFieldPath: spec.forProvider.externalNetworkId
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: status.subnetId
                toFieldPath: spec.forProvider.externalSubnetIds[0]
                policy:
                  fromFieldPath: Required
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.routerId
