apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsessionkey
  labels:
    provider: random
spec:
  compositeTypeRef:
    apiVersion: rpcu.io/v1alpha1
    kind: XSessionKey
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
    - name: common
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
  resources:
    - name: session-key
      base:
        apiVersion: random.crossplane.io/v1beta1
        kind: String
        spec:
          length: 32
          charset: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.length
          toFieldPath: spec.length
      connectionDetailsLastPublishedTimeFieldPath: status.conditions[0].lastTransitionTime
