apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: externalnetworks.networking.rpcu.io
spec:
  scope: Namespaced
  group: networking.rpcu.io
  names:
    kind: ExternalNetwork
    plural: externalnetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routerName:
                  type: string
                  description: Name of the router in OpenStack
                networkName:
                  type: string
                  description: Name of the external gateway NetworkV2 resource
                subnetName:
                  type: string
                  description: Name of the external subnet resource
                cidr:
                  type: string
                  description: CIDR for the subnet resource
              required:
                - routerName
                - subnetName
                - networkName
                - cidr
            status:
              type: object
              properties:
                networkId:
                  type: string
                  description: Resolved external network ID from OpenStack
                routerId:
                  type: string
                  description: Router ID from OpenStack
                subnetId:
                  type: string
                  description: Subnet ID from OpenStack
