apiVersion: networking.rpcu.io/v1alpha1
kind: ExternalNetwork
metadata:
  name: ext
spec:
  routerName: ext
  networkName: ext
  subnetName: ext
  cidr: 172.16.0.0/16
  gatewayIp: 172.16.0.254
  dnsNameservers:
    - 1.1.1.1
    - 1.0.0.1
  allocationPool:
    - start: 172.16.255.1
      end: 172.16.255.254
