apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: GroupV3
metadata:
  name: admins
spec:
  forProvider:
    description: admins
    name: admins
---
apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  name: admin
  annotations:
    crossplane.io/external-name: "222436f91fc640ba9e64c67b5779573f"
spec:
  forProvider:
    name: admin
---
apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: RoleAssignmentV3
metadata:
  name: admins
spec:
  forProvider:
    roleIdRef:
      name: admin
    groupId: "1b2083fcdcf5419397ba2e4091da0b62"
    projectIdRef:
      name: admin
