apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: GroupV3
metadata:
  name: admins
spec:
  forProvider:
    description: admins
    name: admins
---
apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  name: admin
  annotations:
    crossplane.io/external-name: "af51259b8601414880f6af3bfd5a8022"
spec:
  forProvider:
    name: admin
---
apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: RoleAssignmentV3
metadata:
  name: admins
spec:
  forProvider:
    roleIdRef:
      name: admin
    groupId: "06aa1b3667ac4d5196632127eef6969f"
    projectIdRef:
      name: admin
