namespace: yaook
resources:
  - network-default.yaml
  - network-lbext.yaml
  - providerConfig.yaml
  - externalnetwork.yaml
  - flavors.yaml
  - groups.yaml
  - projects.yaml
  - securityGroups.yaml
