namespace: yaook
resources:
  - network-default.yaml
  - providerConfig.yaml
  - externalnetwork.yaml
  - flavors.yaml
  - groups.yaml
  - project-admin.yaml
  - project-production.yaml
  - securityGroups.yaml
  - zonedns.yaml
