apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  name: default
spec:
  forProvider:
    adminStateUp: true
    shared: false
    mtu: 8942
    name: default
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  name: default
spec:
  forProvider:
    name: default
    cidr: 192.168.0.0/24
    networkIdRef:
      name: default
    enableDhcp: true
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  name: defaultext
spec:
  forProvider:
    routerIdRef:
      name: ext
    subnetIdRef:
      name: default
