apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  name: lbext
spec:
  forProvider:
    adminStateUp: true
    shared: false
    name: lbext
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  name: lbext
spec:
  forProvider:
    name: lbext
    cidr: 172.17.0.0/16
    dnsNameservers:
      - 1.1.1.1
      - 1.0.0.1
    networkIdRef:
      name: lbext
    enableDhcp: true
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  name: lbext
spec:
  forProvider:
    routerIdRef:
      name: ext
    subnetIdRef:
      name: lbext
