apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  name: mgmt
spec:
  forProvider:
    adminStateUp: true
    shared: false
    name: mgmt
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  name: mgmt
spec:
  forProvider:
    name: mgmt
    cidr: 192.168.0.0/24
    dnsNameservers:
      - 1.1.1.1
      - 1.0.0.1
    networkIdRef:
      name: mgmt
    enableDhcp: true
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  name: mgmtext
spec:
  forProvider:
    routerIdRef:
      name: ext
    subnetIdRef:
      name: mgmt
