apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  labels:
    network: ext
  name: ext
spec:
  forProvider:
    cidr: 172.16.0.0/16
    networkIdSelector:
      matchLabels:
        network: ext
---

