apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  name: default
spec:
  forProvider:
    adminStateUp: true
    shared: false
    mtu: 8942
    name: default
    dnsDomain: default.openstack.rpcu.vpn.
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  name: default
spec:
  forProvider:
    name: default
    cidr: 192.168.0.0/24
    dnsPublishFixedIp: true
    dnsNameservers:
      - 1.1.1.1
      - 1.0.0.1
    networkIdRef:
      name: default
    enableDhcp: true
---
apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: RouterInterfaceV2
metadata:
  name: defaultext
spec:
  forProvider:
    routerIdRef:
      name: ext
    subnetIdRef:
      name: default
