resources:
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - trust-manager.yaml
  - gateway-api.yaml
  - kgateway-crds.yaml
  - kgateway.yaml
  - cilium.yaml
  - flux-operator.yaml
  - rook.yaml
  - yaook-operator.yaml
  - fluxcd/
