resources:
  - coredns-cm.yaml
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - trust-manager.yaml
  - gateway-api.yaml
  - kgateway-crds.yaml
  - kgateway.yaml
  - cilium.yaml
  - crossplane.yaml
  - external-secrets.yaml
  - flux-operator.yaml
  - rook.yaml
  - monitoring.yaml
  - blackbox.yaml
  - blackbox-probes.yaml
  - openstack-exporter.yaml
  - golinky.yaml
  - yaook-operator.yaml
  - fluxcd/
