apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
spec:
  interval: 30m
  chart:
    spec:
      chart: contour
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: contour
        namespace: projectcontour
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
